In [3]:
import pandas as pd
import numpy as np
pd.options.mode.chained_assignment = None  # default='warn'

In [4]:
source_file="MonthlyCSVs/AirLineCountCumulavtive.csv"

In [5]:
df_al=pd.read_csv("MonthlyCSVs/Airline_Lookup.csv")
df_al

   IATA_Airline               AirlineName
0            9E               Endeavor Air
1            AA          American Airlines
2            AS            Alaska Airlines
3            B6            Jetblue Airways
4            DL            Delta Air Lines
5            EV       Express Jet Airlines
6            F9          Frontier Airlines
7            G4              Allegiant Air
8            HA          Hawaiian Airlines
9            MQ                  Envoy Air
10           NK            Spirit Airlines
11           OH               PSA Airlines
12           OO           SkyWest Airlines
13           UA            United Airlines
14           US  Puerto Rico Intl Airlines
15           VX             Virgin America
16           WN         Southwest Airlines
17           YV              Mesa Airlines
18           YX           Republic Airways

In [6]:
df_source=pd.read_csv(source_file)
df_source

,IATA_Airline,2015-01,2015-02,2015-03,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,...,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12
0,9E,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,298609.0,319191.0,340021.0,361257.0,382761.0,405384.0,426153.0,447528.0,468288.0,491350.0
1,AA,43074.0,80254.0,124694.0,168873.0,212484.0,256098.0,336748.0,415456.0,488344.0,...,3619700.0,3693618.0,3772266.0,3848334.0,3927228.0,4007785.0,4084208.0,4164165.0,4241240.0,4320334.0
2,AS,13151.0,25179.0,39375.0,53260.0,67865.0,82850.0,98581.0,114612.0,128844.0,...,833112.0,854194.0,876602.0,899615.0,924003.0,948409.0,969985.0,992011.0,1012801.0,1034502.0
3,B6,20482.0,38865.0,60892.0,82707.0,105059.0,127305.0,151052.0,174558.0,195565.0,...,1198265.0,1223163.0,1247950.0,1272033.0,1297073.0,1322245.0,1345824.0,1370555.0,1395199.0,1420162.0
4,DL,63676.0,122746.0,196253.0,268149.0,342620.0,419380.0,499766.0,580441.0,652391.0,...,3868385.0,3950028.0,4035385.0,4122230.0,4212329.0,4303167.0,4384321.0,4470500.0,4550420.0,4631825.0
5,EV,48084.0,90089.0,141964.0,190099.0,238037.0,285191.0,334512.0,382180.0,425547.0,...,1592980.0,1603394.0,1612099.0,1621228.0,1631804.0,1642441.0,1653304.0,1663610.0,1674682.0,1685613.0
6,F9,6735.0,12426.0,19306.0,26398.0,34473.0,42287.0,50325.0,58428.0,66274.0,...,431100.0,440725.0,451955.0,463262.0,475477.0,487714.0,499593.0,512152.0,524269.0,536384.0
7,G4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,119246.0,128441.0,137423.0,148410.0,160128.0,168808.0,174384.0,182231.0,190339.0,199635.0
8,HA,6408.0,12181.0,18475.0,24554.0,30972.0,37635.0,44571.0,51421.0,57548.0,...,335509.0,342398.0,349613.0,356776.0,364099.0,371445.0,378298.0,385398.0,392286.0,399553.0
9,MQ,27568.0,50560.0,76622.0,101350.0,125755.0,149746.0,173793.0,196909.0,217708.0,...,635123.0,660186.0,687865.0,714885.0,743053.0,771844.0,798271.0,825841.0,851313.0,877946.0
10,NK,8632.0,16445.0,25699.0,35114.0,44914.0,54239.0,64441.0,74668.0,84536.0,...,621626.0,637910.0,655672.0,673165.0,691532.0,709796.0,725769.0,742544.0,759876.0,777052.0
11,OH,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,332510.0,355858.0,380040.0,404119.0,428434.0,452841.0,476002.0,500149.0,523500.0,547431.0
12,OO,46655.0,89104.0,138539.0,187034.0,236162.0,285220.0,336878.0,388664.0,435871.0,...,2813930.0,2880825.0,2951423.0,3022326.0,3094812.0,3168675.0,3235169.0,3306617.0,3372908.0,3443041.0
13,UA,37363.0,72535.0,115406.0,156271.0,200135.0,244880.0,290753.0,335694.0,377296.0,...,2380558.0,2432196.0,2485910.0,2539364.0,2594428.0,2649931.0,2701036.0,2755868.0,2805726.0,2856786.0
14,US,32478.0,60987.0,94634.0,126885.0,160334.0,194223.0,194223.0,194223.0,194223.0,...,194223.0,194223.0,194223.0,194223.0,194223.0,194223.0,194223.0,194223.0,194223.0,194223.0
15,VX,4647.0,8701.0,13497.0,18393.0,23588.0,28815.0,34199.0,39857.0,44998.0,...,216340.0,216340.0,216340.0,216340.0,216340.0,216340.0,216340.0,216340.0,216340.0,216340.0
16,WN,98060.0,184604.0,291458.0,396978.0,503308.0,610684.0,723095.0,829782.0,929901.0,...,5479426.0,5589913.0,5703254.0,5815717.0,5933112.0,6047845.0,6155097.0,6269967.0,6377966.0,6491077.0
17,YV,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,261210.0,278848.0,297388.0,316186.0,335620.0,354946.0,373436.0,392767.0,411193.0,429680.0
18,YX,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,379499.0,405920.0,433281.0,460127.0,486922.0,514890.0,542032.0,570616.0,597620.0,625867.0

In [7]:
df_merge=pd.merge(df_al,df_source,on='IATA_Airline')
df_merge

,IATA_Airline,AirlineName,2015-01,2015-02,2015-03,2015-04,2015-05,2015-06,2015-07,2015-08,...,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12
0,9E,Endeavor Air,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,298609.0,319191.0,340021.0,361257.0,382761.0,405384.0,426153.0,447528.0,468288.0,491350.0
1,AA,American Airlines,43074.0,80254.0,124694.0,168873.0,212484.0,256098.0,336748.0,415456.0,...,3619700.0,3693618.0,3772266.0,3848334.0,3927228.0,4007785.0,4084208.0,4164165.0,4241240.0,4320334.0
2,AS,Alaska Airlines,13151.0,25179.0,39375.0,53260.0,67865.0,82850.0,98581.0,114612.0,...,833112.0,854194.0,876602.0,899615.0,924003.0,948409.0,969985.0,992011.0,1012801.0,1034502.0
3,B6,Jetblue Airways,20482.0,38865.0,60892.0,82707.0,105059.0,127305.0,151052.0,174558.0,...,1198265.0,1223163.0,1247950.0,1272033.0,1297073.0,1322245.0,1345824.0,1370555.0,1395199.0,1420162.0
4,DL,Delta Air Lines,63676.0,122746.0,196253.0,268149.0,342620.0,419380.0,499766.0,580441.0,...,3868385.0,3950028.0,4035385.0,4122230.0,4212329.0,4303167.0,4384321.0,4470500.0,4550420.0,4631825.0
5,EV,Express Jet Airlines,48084.0,90089.0,141964.0,190099.0,238037.0,285191.0,334512.0,382180.0,...,1592980.0,1603394.0,1612099.0,1621228.0,1631804.0,1642441.0,1653304.0,1663610.0,1674682.0,1685613.0
6,F9,Frontier Airlines,6735.0,12426.0,19306.0,26398.0,34473.0,42287.0,50325.0,58428.0,...,431100.0,440725.0,451955.0,463262.0,475477.0,487714.0,499593.0,512152.0,524269.0,536384.0
7,G4,Allegiant Air,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,119246.0,128441.0,137423.0,148410.0,160128.0,168808.0,174384.0,182231.0,190339.0,199635.0
8,HA,Hawaiian Airlines,6408.0,12181.0,18475.0,24554.0,30972.0,37635.0,44571.0,51421.0,...,335509.0,342398.0,349613.0,356776.0,364099.0,371445.0,378298.0,385398.0,392286.0,399553.0
9,MQ,Envoy Air,27568.0,50560.0,76622.0,101350.0,125755.0,149746.0,173793.0,196909.0,...,635123.0,660186.0,687865.0,714885.0,743053.0,771844.0,798271.0,825841.0,851313.0,877946.0
10,NK,Spirit Airlines,8632.0,16445.0,25699.0,35114.0,44914.0,54239.0,64441.0,74668.0,...,621626.0,637910.0,655672.0,673165.0,691532.0,709796.0,725769.0,742544.0,759876.0,777052.0
11,OH,PSA Airlines,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,332510.0,355858.0,380040.0,404119.0,428434.0,452841.0,476002.0,500149.0,523500.0,547431.0
12,OO,SkyWest Airlines,46655.0,89104.0,138539.0,187034.0,236162.0,285220.0,336878.0,388664.0,...,2813930.0,2880825.0,2951423.0,3022326.0,3094812.0,3168675.0,3235169.0,3306617.0,3372908.0,3443041.0
13,UA,United Airlines,37363.0,72535.0,115406.0,156271.0,200135.0,244880.0,290753.0,335694.0,...,2380558.0,2432196.0,2485910.0,2539364.0,2594428.0,2649931.0,2701036.0,2755868.0,2805726.0,2856786.0
14,US,Puerto Rico Intl Airlines,32478.0,60987.0,94634.0,126885.0,160334.0,194223.0,194223.0,194223.0,...,194223.0,194223.0,194223.0,194223.0,194223.0,194223.0,194223.0,194223.0,194223.0,194223.0
15,VX,Virgin America,4647.0,8701.0,13497.0,18393.0,23588.0,28815.0,34199.0,39857.0,...,216340.0,216340.0,216340.0,216340.0,216340.0,216340.0,216340.0,216340.0,216340.0,216340.0
16,WN,Southwest Airlines,98060.0,184604.0,291458.0,396978.0,503308.0,610684.0,723095.0,829782.0,...,5479426.0,5589913.0,5703254.0,5815717.0,5933112.0,6047845.0,6155097.0,6269967.0,6377966.0,6491077.0
17,YV,Mesa Airlines,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,261210.0,278848.0,297388.0,316186.0,335620.0,354946.0,373436.0,392767.0,411193.0,429680.0
18,YX,Republic Airways,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,379499.0,405920.0,433281.0,460127.0,486922.0,514890.0,542032.0,570616.0,597620.0,625867.0

In [8]:
df_merge.drop('IATA_Airline', axis=1, inplace=True)
df_merge

,AirlineName,2015-01,2015-02,2015-03,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,...,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12
0,Endeavor Air,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,298609.0,319191.0,340021.0,361257.0,382761.0,405384.0,426153.0,447528.0,468288.0,491350.0
1,American Airlines,43074.0,80254.0,124694.0,168873.0,212484.0,256098.0,336748.0,415456.0,488344.0,...,3619700.0,3693618.0,3772266.0,3848334.0,3927228.0,4007785.0,4084208.0,4164165.0,4241240.0,4320334.0
2,Alaska Airlines,13151.0,25179.0,39375.0,53260.0,67865.0,82850.0,98581.0,114612.0,128844.0,...,833112.0,854194.0,876602.0,899615.0,924003.0,948409.0,969985.0,992011.0,1012801.0,1034502.0
3,Jetblue Airways,20482.0,38865.0,60892.0,82707.0,105059.0,127305.0,151052.0,174558.0,195565.0,...,1198265.0,1223163.0,1247950.0,1272033.0,1297073.0,1322245.0,1345824.0,1370555.0,1395199.0,1420162.0
4,Delta Air Lines,63676.0,122746.0,196253.0,268149.0,342620.0,419380.0,499766.0,580441.0,652391.0,...,3868385.0,3950028.0,4035385.0,4122230.0,4212329.0,4303167.0,4384321.0,4470500.0,4550420.0,4631825.0
5,Express Jet Airlines,48084.0,90089.0,141964.0,190099.0,238037.0,285191.0,334512.0,382180.0,425547.0,...,1592980.0,1603394.0,1612099.0,1621228.0,1631804.0,1642441.0,1653304.0,1663610.0,1674682.0,1685613.0
6,Frontier Airlines,6735.0,12426.0,19306.0,26398.0,34473.0,42287.0,50325.0,58428.0,66274.0,...,431100.0,440725.0,451955.0,463262.0,475477.0,487714.0,499593.0,512152.0,524269.0,536384.0
7,Allegiant Air,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,119246.0,128441.0,137423.0,148410.0,160128.0,168808.0,174384.0,182231.0,190339.0,199635.0
8,Hawaiian Airlines,6408.0,12181.0,18475.0,24554.0,30972.0,37635.0,44571.0,51421.0,57548.0,...,335509.0,342398.0,349613.0,356776.0,364099.0,371445.0,378298.0,385398.0,392286.0,399553.0
9,Envoy Air,27568.0,50560.0,76622.0,101350.0,125755.0,149746.0,173793.0,196909.0,217708.0,...,635123.0,660186.0,687865.0,714885.0,743053.0,771844.0,798271.0,825841.0,851313.0,877946.0
10,Spirit Airlines,8632.0,16445.0,25699.0,35114.0,44914.0,54239.0,64441.0,74668.0,84536.0,...,621626.0,637910.0,655672.0,673165.0,691532.0,709796.0,725769.0,742544.0,759876.0,777052.0
11,PSA Airlines,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,332510.0,355858.0,380040.0,404119.0,428434.0,452841.0,476002.0,500149.0,523500.0,547431.0
12,SkyWest Airlines,46655.0,89104.0,138539.0,187034.0,236162.0,285220.0,336878.0,388664.0,435871.0,...,2813930.0,2880825.0,2951423.0,3022326.0,3094812.0,3168675.0,3235169.0,3306617.0,3372908.0,3443041.0
13,United Airlines,37363.0,72535.0,115406.0,156271.0,200135.0,244880.0,290753.0,335694.0,377296.0,...,2380558.0,2432196.0,2485910.0,2539364.0,2594428.0,2649931.0,2701036.0,2755868.0,2805726.0,2856786.0
14,Puerto Rico Intl Airlines,32478.0,60987.0,94634.0,126885.0,160334.0,194223.0,194223.0,194223.0,194223.0,...,194223.0,194223.0,194223.0,194223.0,194223.0,194223.0,194223.0,194223.0,194223.0,194223.0
15,Virgin America,4647.0,8701.0,13497.0,18393.0,23588.0,28815.0,34199.0,39857.0,44998.0,...,216340.0,216340.0,216340.0,216340.0,216340.0,216340.0,216340.0,216340.0,216340.0,216340.0
16,Southwest Airlines,98060.0,184604.0,291458.0,396978.0,503308.0,610684.0,723095.0,829782.0,929901.0,...,5479426.0,5589913.0,5703254.0,5815717.0,5933112.0,6047845.0,6155097.0,6269967.0,6377966.0,6491077.0
17,Mesa Airlines,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,261210.0,278848.0,297388.0,316186.0,335620.0,354946.0,373436.0,392767.0,411193.0,429680.0
18,Republic Airways,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,379499.0,405920.0,433281.0,460127.0,486922.0,514890.0,542032.0,570616.0,597620.0,625867.0

In [9]:
df_merge

,AirlineName,2015-01,2015-02,2015-03,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,...,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12
0,Endeavor Air,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,298609.0,319191.0,340021.0,361257.0,382761.0,405384.0,426153.0,447528.0,468288.0,491350.0
1,American Airlines,43074.0,80254.0,124694.0,168873.0,212484.0,256098.0,336748.0,415456.0,488344.0,...,3619700.0,3693618.0,3772266.0,3848334.0,3927228.0,4007785.0,4084208.0,4164165.0,4241240.0,4320334.0
2,Alaska Airlines,13151.0,25179.0,39375.0,53260.0,67865.0,82850.0,98581.0,114612.0,128844.0,...,833112.0,854194.0,876602.0,899615.0,924003.0,948409.0,969985.0,992011.0,1012801.0,1034502.0
3,Jetblue Airways,20482.0,38865.0,60892.0,82707.0,105059.0,127305.0,151052.0,174558.0,195565.0,...,1198265.0,1223163.0,1247950.0,1272033.0,1297073.0,1322245.0,1345824.0,1370555.0,1395199.0,1420162.0
4,Delta Air Lines,63676.0,122746.0,196253.0,268149.0,342620.0,419380.0,499766.0,580441.0,652391.0,...,3868385.0,3950028.0,4035385.0,4122230.0,4212329.0,4303167.0,4384321.0,4470500.0,4550420.0,4631825.0
5,Express Jet Airlines,48084.0,90089.0,141964.0,190099.0,238037.0,285191.0,334512.0,382180.0,425547.0,...,1592980.0,1603394.0,1612099.0,1621228.0,1631804.0,1642441.0,1653304.0,1663610.0,1674682.0,1685613.0
6,Frontier Airlines,6735.0,12426.0,19306.0,26398.0,34473.0,42287.0,50325.0,58428.0,66274.0,...,431100.0,440725.0,451955.0,463262.0,475477.0,487714.0,499593.0,512152.0,524269.0,536384.0
7,Allegiant Air,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,119246.0,128441.0,137423.0,148410.0,160128.0,168808.0,174384.0,182231.0,190339.0,199635.0
8,Hawaiian Airlines,6408.0,12181.0,18475.0,24554.0,30972.0,37635.0,44571.0,51421.0,57548.0,...,335509.0,342398.0,349613.0,356776.0,364099.0,371445.0,378298.0,385398.0,392286.0,399553.0
9,Envoy Air,27568.0,50560.0,76622.0,101350.0,125755.0,149746.0,173793.0,196909.0,217708.0,...,635123.0,660186.0,687865.0,714885.0,743053.0,771844.0,798271.0,825841.0,851313.0,877946.0
10,Spirit Airlines,8632.0,16445.0,25699.0,35114.0,44914.0,54239.0,64441.0,74668.0,84536.0,...,621626.0,637910.0,655672.0,673165.0,691532.0,709796.0,725769.0,742544.0,759876.0,777052.0
11,PSA Airlines,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,332510.0,355858.0,380040.0,404119.0,428434.0,452841.0,476002.0,500149.0,523500.0,547431.0
12,SkyWest Airlines,46655.0,89104.0,138539.0,187034.0,236162.0,285220.0,336878.0,388664.0,435871.0,...,2813930.0,2880825.0,2951423.0,3022326.0,3094812.0,3168675.0,3235169.0,3306617.0,3372908.0,3443041.0
13,United Airlines,37363.0,72535.0,115406.0,156271.0,200135.0,244880.0,290753.0,335694.0,377296.0,...,2380558.0,2432196.0,2485910.0,2539364.0,2594428.0,2649931.0,2701036.0,2755868.0,2805726.0,2856786.0
14,Puerto Rico Intl Airlines,32478.0,60987.0,94634.0,126885.0,160334.0,194223.0,194223.0,194223.0,194223.0,...,194223.0,194223.0,194223.0,194223.0,194223.0,194223.0,194223.0,194223.0,194223.0,194223.0
15,Virgin America,4647.0,8701.0,13497.0,18393.0,23588.0,28815.0,34199.0,39857.0,44998.0,...,216340.0,216340.0,216340.0,216340.0,216340.0,216340.0,216340.0,216340.0,216340.0,216340.0
16,Southwest Airlines,98060.0,184604.0,291458.0,396978.0,503308.0,610684.0,723095.0,829782.0,929901.0,...,5479426.0,5589913.0,5703254.0,5815717.0,5933112.0,6047845.0,6155097.0,6269967.0,6377966.0,6491077.0
17,Mesa Airlines,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,261210.0,278848.0,297388.0,316186.0,335620.0,354946.0,373436.0,392767.0,411193.0,429680.0
18,Republic Airways,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,379499.0,405920.0,433281.0,460127.0,486922.0,514890.0,542032.0,570616.0,597620.0,625867.0

In [10]:
new_columns = df_merge.columns.values
new_columns[0] = 'IATA_Airline'
df_merge.columns = new_columns
df_merge

,IATA_Airline,2015-01,2015-02,2015-03,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,...,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12
0,Endeavor Air,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,298609.0,319191.0,340021.0,361257.0,382761.0,405384.0,426153.0,447528.0,468288.0,491350.0
1,American Airlines,43074.0,80254.0,124694.0,168873.0,212484.0,256098.0,336748.0,415456.0,488344.0,...,3619700.0,3693618.0,3772266.0,3848334.0,3927228.0,4007785.0,4084208.0,4164165.0,4241240.0,4320334.0
2,Alaska Airlines,13151.0,25179.0,39375.0,53260.0,67865.0,82850.0,98581.0,114612.0,128844.0,...,833112.0,854194.0,876602.0,899615.0,924003.0,948409.0,969985.0,992011.0,1012801.0,1034502.0
3,Jetblue Airways,20482.0,38865.0,60892.0,82707.0,105059.0,127305.0,151052.0,174558.0,195565.0,...,1198265.0,1223163.0,1247950.0,1272033.0,1297073.0,1322245.0,1345824.0,1370555.0,1395199.0,1420162.0
4,Delta Air Lines,63676.0,122746.0,196253.0,268149.0,342620.0,419380.0,499766.0,580441.0,652391.0,...,3868385.0,3950028.0,4035385.0,4122230.0,4212329.0,4303167.0,4384321.0,4470500.0,4550420.0,4631825.0
5,Express Jet Airlines,48084.0,90089.0,141964.0,190099.0,238037.0,285191.0,334512.0,382180.0,425547.0,...,1592980.0,1603394.0,1612099.0,1621228.0,1631804.0,1642441.0,1653304.0,1663610.0,1674682.0,1685613.0
6,Frontier Airlines,6735.0,12426.0,19306.0,26398.0,34473.0,42287.0,50325.0,58428.0,66274.0,...,431100.0,440725.0,451955.0,463262.0,475477.0,487714.0,499593.0,512152.0,524269.0,536384.0
7,Allegiant Air,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,119246.0,128441.0,137423.0,148410.0,160128.0,168808.0,174384.0,182231.0,190339.0,199635.0
8,Hawaiian Airlines,6408.0,12181.0,18475.0,24554.0,30972.0,37635.0,44571.0,51421.0,57548.0,...,335509.0,342398.0,349613.0,356776.0,364099.0,371445.0,378298.0,385398.0,392286.0,399553.0
9,Envoy Air,27568.0,50560.0,76622.0,101350.0,125755.0,149746.0,173793.0,196909.0,217708.0,...,635123.0,660186.0,687865.0,714885.0,743053.0,771844.0,798271.0,825841.0,851313.0,877946.0
10,Spirit Airlines,8632.0,16445.0,25699.0,35114.0,44914.0,54239.0,64441.0,74668.0,84536.0,...,621626.0,637910.0,655672.0,673165.0,691532.0,709796.0,725769.0,742544.0,759876.0,777052.0
11,PSA Airlines,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,332510.0,355858.0,380040.0,404119.0,428434.0,452841.0,476002.0,500149.0,523500.0,547431.0
12,SkyWest Airlines,46655.0,89104.0,138539.0,187034.0,236162.0,285220.0,336878.0,388664.0,435871.0,...,2813930.0,2880825.0,2951423.0,3022326.0,3094812.0,3168675.0,3235169.0,3306617.0,3372908.0,3443041.0
13,United Airlines,37363.0,72535.0,115406.0,156271.0,200135.0,244880.0,290753.0,335694.0,377296.0,...,2380558.0,2432196.0,2485910.0,2539364.0,2594428.0,2649931.0,2701036.0,2755868.0,2805726.0,2856786.0
14,Puerto Rico Intl Airlines,32478.0,60987.0,94634.0,126885.0,160334.0,194223.0,194223.0,194223.0,194223.0,...,194223.0,194223.0,194223.0,194223.0,194223.0,194223.0,194223.0,194223.0,194223.0,194223.0
15,Virgin America,4647.0,8701.0,13497.0,18393.0,23588.0,28815.0,34199.0,39857.0,44998.0,...,216340.0,216340.0,216340.0,216340.0,216340.0,216340.0,216340.0,216340.0,216340.0,216340.0
16,Southwest Airlines,98060.0,184604.0,291458.0,396978.0,503308.0,610684.0,723095.0,829782.0,929901.0,...,5479426.0,5589913.0,5703254.0,5815717.0,5933112.0,6047845.0,6155097.0,6269967.0,6377966.0,6491077.0
17,Mesa Airlines,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,261210.0,278848.0,297388.0,316186.0,335620.0,354946.0,373436.0,392767.0,411193.0,429680.0
18,Republic Airways,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,379499.0,405920.0,433281.0,460127.0,486922.0,514890.0,542032.0,570616.0,597620.0,625867.0

In [11]:
df_merge = df_merge.sort_values(by=df_merge.columns[1], ascending=False)
df_merge

,IATA_Airline,2015-01,2015-02,2015-03,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,...,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12
16,Southwest Airlines,98060.0,184604.0,291458.0,396978.0,503308.0,610684.0,723095.0,829782.0,929901.0,...,5479426.0,5589913.0,5703254.0,5815717.0,5933112.0,6047845.0,6155097.0,6269967.0,6377966.0,6491077.0
4,Delta Air Lines,63676.0,122746.0,196253.0,268149.0,342620.0,419380.0,499766.0,580441.0,652391.0,...,3868385.0,3950028.0,4035385.0,4122230.0,4212329.0,4303167.0,4384321.0,4470500.0,4550420.0,4631825.0
5,Express Jet Airlines,48084.0,90089.0,141964.0,190099.0,238037.0,285191.0,334512.0,382180.0,425547.0,...,1592980.0,1603394.0,1612099.0,1621228.0,1631804.0,1642441.0,1653304.0,1663610.0,1674682.0,1685613.0
12,SkyWest Airlines,46655.0,89104.0,138539.0,187034.0,236162.0,285220.0,336878.0,388664.0,435871.0,...,2813930.0,2880825.0,2951423.0,3022326.0,3094812.0,3168675.0,3235169.0,3306617.0,3372908.0,3443041.0
1,American Airlines,43074.0,80254.0,124694.0,168873.0,212484.0,256098.0,336748.0,415456.0,488344.0,...,3619700.0,3693618.0,3772266.0,3848334.0,3927228.0,4007785.0,4084208.0,4164165.0,4241240.0,4320334.0
13,United Airlines,37363.0,72535.0,115406.0,156271.0,200135.0,244880.0,290753.0,335694.0,377296.0,...,2380558.0,2432196.0,2485910.0,2539364.0,2594428.0,2649931.0,2701036.0,2755868.0,2805726.0,2856786.0
14,Puerto Rico Intl Airlines,32478.0,60987.0,94634.0,126885.0,160334.0,194223.0,194223.0,194223.0,194223.0,...,194223.0,194223.0,194223.0,194223.0,194223.0,194223.0,194223.0,194223.0,194223.0,194223.0
9,Envoy Air,27568.0,50560.0,76622.0,101350.0,125755.0,149746.0,173793.0,196909.0,217708.0,...,635123.0,660186.0,687865.0,714885.0,743053.0,771844.0,798271.0,825841.0,851313.0,877946.0
3,Jetblue Airways,20482.0,38865.0,60892.0,82707.0,105059.0,127305.0,151052.0,174558.0,195565.0,...,1198265.0,1223163.0,1247950.0,1272033.0,1297073.0,1322245.0,1345824.0,1370555.0,1395199.0,1420162.0
2,Alaska Airlines,13151.0,25179.0,39375.0,53260.0,67865.0,82850.0,98581.0,114612.0,128844.0,...,833112.0,854194.0,876602.0,899615.0,924003.0,948409.0,969985.0,992011.0,1012801.0,1034502.0
10,Spirit Airlines,8632.0,16445.0,25699.0,35114.0,44914.0,54239.0,64441.0,74668.0,84536.0,...,621626.0,637910.0,655672.0,673165.0,691532.0,709796.0,725769.0,742544.0,759876.0,777052.0
6,Frontier Airlines,6735.0,12426.0,19306.0,26398.0,34473.0,42287.0,50325.0,58428.0,66274.0,...,431100.0,440725.0,451955.0,463262.0,475477.0,487714.0,499593.0,512152.0,524269.0,536384.0
8,Hawaiian Airlines,6408.0,12181.0,18475.0,24554.0,30972.0,37635.0,44571.0,51421.0,57548.0,...,335509.0,342398.0,349613.0,356776.0,364099.0,371445.0,378298.0,385398.0,392286.0,399553.0
15,Virgin America,4647.0,8701.0,13497.0,18393.0,23588.0,28815.0,34199.0,39857.0,44998.0,...,216340.0,216340.0,216340.0,216340.0,216340.0,216340.0,216340.0,216340.0,216340.0,216340.0
17,Mesa Airlines,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,261210.0,278848.0,297388.0,316186.0,335620.0,354946.0,373436.0,392767.0,411193.0,429680.0
0,Endeavor Air,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,298609.0,319191.0,340021.0,361257.0,382761.0,405384.0,426153.0,447528.0,468288.0,491350.0
11,PSA Airlines,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,332510.0,355858.0,380040.0,404119.0,428434.0,452841.0,476002.0,500149.0,523500.0,547431.0
7,Allegiant Air,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,119246.0,128441.0,137423.0,148410.0,160128.0,168808.0,174384.0,182231.0,190339.0,199635.0
18,Republic Airways,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,379499.0,405920.0,433281.0,460127.0,486922.0,514890.0,542032.0,570616.0,597620.0,625867.0

In [13]:
df_merge.to_csv(source_file,index=False)